# Generated by Django 4.0.5 on 2022-07-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Poyezd nomi')),
                ('travel_time', models.PositiveSmallIntegerField(verbose_name="Yo'l vaqti")),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='cities.city', verbose_name='Qaysi shahardan')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='cities.city', verbose_name='Qaysi shaharga')),
            ],
            options={
                'verbose_name': 'Poyezd',
                'verbose_name_plural': 'Poyezdlar',
                'ordering': ['travel_time'],
            },
        ),
    ]
