# Generated by Django 4.0.5 on 2022-06-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_city_name'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='cities.city', verbose_name='Qaysi shahardan'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Poyezd nomi'),
        ),
        migrations.AlterField(
            model_name='train',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='cities.city', verbose_name='Qaysi shaharga'),
        ),
        migrations.AlterField(
            model_name='train',
            name='travel_time',
            field=models.PositiveSmallIntegerField(verbose_name="Yo'l vaqti"),
        ),
    ]
