# Generated by Django 4.0.5 on 2022-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
