# Generated by Django 4.0.5 on 2022-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_travel_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='travel_times',
            field=models.PositiveSmallIntegerField(verbose_name="Umumiy yo'l vaqti"),
        ),
    ]
