# Generated by Django 4.0.5 on 2022-06-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
