# Generated by Django 4.0.5 on 2022-06-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Shahar', 'verbose_name_plural': 'Shaharlar'},
        ),
    ]
