# Generated by Django 4.0.5 on 2022-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Marshrut nomi'),
        ),
    ]
