# Generated by Django 4.0.5 on 2022-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='travel_times',
            field=models.IntegerField(verbose_name="Umumiy yo'l vaqti"),
        ),
    ]
